### ISSUE TITLE
Set avatar when creating project

### ISSUE THREAD

**Issue by quentint** [jdalrymple/gitbeaker#3003]
Hi and thanks for such an awesome library 👍 

I'm trying to create a project with an avatar/image. Here's how my code looks:

```ts
project = await api.Projects.create({
  path: mediaId,
  name: `${mediaId} - ${response.data.title}`,
  namespaceId: parentGroupIp,
  avatar: `@${mediaId}.png`,
})
```

But unfortunately it fails with `description: 'avatar is invalid'`.

So, here are a few questions:
- is the `avatar` option supported?
- to which directory its path is supposed to be relative? (I also tried an absolute path, but it also failed)
- is the `@` needed/required?
- if setting the avatar on creation is not possible, can we do it later with another method?

Thanks for your help 😉

**Comment by jdalrymple** [comment]
It isnt supported yet, but ill add the functionality. I didnt even know the Gitlab API's projects endpoint supported avatar uploads!

**Comment by jdalrymple** [comment]
Give the latest canary build a look, it should fix this issue!

either pass avatar as a string (url) or an object { content: Blob, filename: string }

**Comment by smithgt** [comment]
Hi @jdalrymple - could we get a canary build for @gitbeaker/browser including this fix, please?  Thanks!

**Comment by jdalrymple** [comment]
@gitbeaker/rest works in browser

**Comment by quentint** [comment]
I tried both with a URL and a `{content, filename}` value, and it failed with `description: 'avatar is invalid'`.  
But these tests were run with `@gitbeaker/node`:`32.2.0--canary.1979.349447020.0`, is this the version I'm supposed to use?

**Comment by jdalrymple** [comment]
Use the canary of @gitbeaker/rest instead. Sorry for the confusion

**Comment by quentint** [comment]
Thanks.

Unfortunately, both formats fail 🙁:

- Using the URL string yields a `Bad Request` error
- Using `{content, filename}`:
  - seems to be ignored (no avatar is shown on the newly created project)
  - breaks the `namespaceId` feature (seems ignored) 🤔

**Comment by smithgt** [comment]
@quentint - I had the same problem and resolved it like this (using GitLab 15.8.1):
```
file=new File([...],"test.png") // or get from a file input
await api.Projects.create({
...
// avatar syntax for @gitbeaker/rest 36.0.2--canary.2258.813948675.0
isForm: true,
avatar: [file, file.name],
})
```

I think the issue is that `file` should be changed to `avatar` on line 200: https://github.com/jdalrymple/gitbeaker/blob/1897-explicit-typing/packages/core/src/resources/Projects.ts#L200

**Comment by quentint** [comment]
Thanks. Unfortunately I could not get it to work in a Node environment. I can't rely on `new File`, and didn't find a way to do the equivalent (my image file is a local one).

**Comment by jdalrymple** [comment]
For node, this is how its done:

```js
const file = new Blob([await FS.readFile('./filename.png')], { type: 'image/png' });

api.Projects.create({
  name: 'Testing title 2',
  avatar: {
    content: file,
    filename: 'avatar.png'
  }
})
```

**Comment by jdalrymple** [comment]
> Give the latest canary build a look, it should fix this issue!
> 
> either pass avatar as a string (url) or an object { content: Blob, filename: string }

I misunderstood the docs, they dont accept image urls from what i can see. I've updated the code types to reflect this

**Comment by quentint** [comment]
Thanks. Unfortunately I'm still stuck.

Here's my code:

```ts
import {Gitlab} from '@gitbeaker/rest'
import fs from "fs"
import { readFile } from 'fs/promises'

const path = require('path')

// (...)

    const options: any = {
      path: mediaId,
      name: `${mediaId} - ${response.data.title}`,
      namespaceId: parentGroupIp,
      description: response.data.description.split('</p>')[0] + '</p>', // Only keep first paragraph, cheap version
    }

    const avatarDir = `\\\\wsl$\\Ubuntu\\home\\quentint\\dev\\edumedia-site\\symfony\\_storage\\import\\media\\lyne`
    const files = fs.readdirSync(avatarDir).filter((file: string) => file.startsWith(mediaId + '-'))
    if (files.length === 1) {
      options.avatar = {
        content: new Blob([await readFile(path.resolve(avatarDir, files[0]))], {type: 'image/png'}),
        filename: files[0]
      }
    }

    try {
      project = await api.Projects.create(options)
    } catch (e) {
      console.error(e)
      this.exit(1)
    }
```

And here's the error:

```
(node:14228) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Bad Request
    at throwFailedRequestError (D:\climt-dev\climt\node_modules\@gitbeaker\rest\dist\index.js:61:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultRequestHandler (D:\climt-dev\climt\node_modules\@gitbeaker\rest\dist\index.js:78:7)
    at async D:\climt-dev\climt\node_modules\@gitbeaker\core\dist\index.js:323:22
    at async EdumediaProjectCreateOnGitLab.run (D:\climt-dev\climt\src\commands\edumedia\project\create-on-gitlab.ts:82:17)
    at async EdumediaProjectCreateOnGitLab._run (D:\climt-dev\climt\node_modules\@oclif\core\lib\command.js:107:22)
    at async Config.runCommand (D:\climt-dev\climt\node_modules\@oclif\core\lib\config\config.js:296:25) {
  [cause]: {
    description: { 'project_namespace.name': [Array], name: [Array], path: [Array] },
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    }
  }
}
```

It might be obvious, but I don't see what's wrong :(

**Comment by quentint** [comment]
You're right, there was a clash with an existing project, sorry about that 🙁.

BUT! Thanks to you guys, I finally got something to work 🙂 

First of all, @smithgt is right, `file: [avatar.content, avatar.filename]` has to be replaced with `avatar: [avatar.content, avatar.filename]` in `Projects.create` because GitLab ignores the `file` file. Unfortunately, the hack he suggests does not work (anymore?), the fix has to be applied on the library side.

And I can confirm the `namespaceId` option is ignored when `avatar` is passed. That seems like a bug on GitLab's side, because what I see in `Projects.create` looks OK to me.

**Comment by jdalrymple** [comment]
Amazing, yes i need to deploy the latest updates that include that! Ill try and get to that today!

**Comment by quentint** [comment]
Just so you know I'm now using this and it works like a charm!

The `namespaceId`/`avatar` issue remains, but seems to be on GitLab's side. For reference, I created an issue here: https://gitlab.com/gitlab-org/gitlab/-/issues/414000 (not sure this is the best repo to report them issues, but I didn't find a better option).
