### ISSUE TITLE
"rejectUnauthorized: false" option is being ignored

### ISSUE THREAD

**Issue by ddsultan** [jdalrymple/gitbeaker#357]
**Description**

I am trying to fetch some user information from a Gitlab server which has a self-signed certificate. With the code:

```
const GitlabAPI = new Gitlab({
      url: this.config.url,
      token: token
});
```

 the `gitlab` module throws an error `"Error: unable to verify the first certificate"`. As the documentation suggests ([https://github.com/jdalrymple/node-gitlab#handling-https-certificates](url)), I did the following:

```
 const api = new Gitlab({
  url: '...',
  token: '...',
  rejectUnauthorized: false
})
```

**Steps to reproduce**

**Expected behaviour**
```
 const api = new Gitlab({
  url: '...',
  token: '...',
  rejectUnauthorized: false
})
``` 
The module should allow insecure certificates.
**Actual behaviour**
The module does not allow insecure certificates even if I pass `rejectUnauthorized: false`

**Comment by jdalrymple** [comment]
Need to update the fetch call to pass agent:

https://github.com/bitinn/node-fetch/issues/15

```
const agent = new https.Agent({
  key: fs.readFileSync(`${CERT_PATH}.key`),
  cert: fs.readFileSync(`${CERT_PATH}.crt`),
  rejectUnauthorized: false
})
```

Ill get around to this soon sorry!

**Comment by dragouf** [comment]
still have this problem with version 11.4.2. Any reason why ? Is something changed ?

**Comment by jdalrymple** [comment]
Not that i know off, but i can give it a look this week!

**Comment by casz** [comment]
How hard can it be to trust a single certificate?

Use the `NODE_EXTRA_CA_CERTS` variable which reads in all certificate loaded in the a pem file.

See https://github.com/node-gitlab/node-gitlab#handling-https-certificates

Why even support this @jdalrymple

**Comment by jdalrymple** [comment]
@casz The only reason i support this is because the underlying request libraries do. It is by no means a good practice to follow lol

**Comment by jdalrymple** [comment]
Ah, this is why it was removed https://github.com/node-gitlab/node-gitlab/commit/f9a47c7beb07d621bc49403e7c0eabb3e3e7b08f#diff-801d926a40f4385a2719a3f3bf308905

**Comment by jdalrymple** [comment]
Ill retest it today, if it still doesnt work, ill remove the option from the library completely. Sorry for the inconvenience

**Comment by jdalrymple** [comment]
Seems to work, ill create a PR

**Comment by dragouf** [comment]
so the functionality was not working and so I don't understand you put a thumb down to my question....

**Comment by jdalrymple** [comment]
@dragouf I was wrong! Sorry about that :)

**Comment by jdalrymple** [comment]
@dragouf I've published it under a beta tag, give it a look when you have a chance!

**Comment by dragouf** [comment]
ok I'll try this week as soon as I can

**Comment by jdalrymple** [comment]
@dragouf Any updates?

**Comment by jdalrymple** [comment]
@dragouf :D?

**Comment by dragouf** [comment]
@jdalrymple sorry for the delay, I have tested it on your branch by doing something like :

```
const api = new Gitlab({
  host: 'https://xxxxx',
  token: 'xxxxx',
  rejectUnauthorized: false
});
```
But I still get `failed, reason: self signed certificate in certificate chain`.

anyway I'm able to bypass it by doing :

`export NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by jdalrymple** [comment]
hmm alright, ill keep looking i guess

**Comment by casz** [comment]
😭 @dragouf why not just add the certificate via NODE_EXTRA_CA_CERTS?

**Comment by dragouf** [comment]
because I don't have the root certificate @casz. It's not me who manage this server in my company and I have no access to it...

**Comment by dragouf** [comment]
@jdalrymple I checked your code and it seems that when you do 

`if (service.url.includes('https') && service.rejectUnauthorized) {`

it's incorrect because rejectUnauthorized is not false by default. when I invert your condition it works.

**Comment by casz** [comment]
just because you don't have the root certificate does not mean you can't retrieve the server certificate and trust just the certificate.

You can also download the root certificate without any difficulty, right from the browser.

https://docs.bvstools.com/home/ssl-documentation/exporting-certificate-authorities-cas-from-a-website
https://unix.stackexchange.com/questions/368123/how-to-extract-the-root-ca-and-subordinate-ca-from-a-certificate-chain-in-linux

**Comment by dragouf** [comment]
About my understanding @casz, client certificate is not a root certificate. And when I try to export the client certificate as a pem file and use NODE_EXTRA_CA_CERTS to list it as additional root certificate, it still tell me that the server certificate is rejected...

**Comment by casz** [comment]
On chrome you should be able to export the root ca as well at least on Windows

**Comment by jdalrymple** [comment]
@dragouf Oops, ill fix my boolean check!

**Comment by jdalrymple** [comment]
> @jdalrymple I checked your code and it seems that when you do
> 
> `if (service.url.includes('https') && service.rejectUnauthorized) {`
> 
> it's incorrect because rejectUnauthorized is not false by default. when I invert your condition it works.

Its true by default...
